FROM node:6-stretch

RUN apt-get update && apt-get install -y netcat

RUN mkdir /usr/src/goof
RUN mkdir /tmp/extracted_files
COPY . /usr/src/goof
WORKDIR /usr/src/goof

RUN npm update
RUN npm install
EXPOSE 3001
EXPOSE 9229

ENTRYPOINT ["./wait-for", "-t", "45", "goof-mongo:27017", "--"]
CMD ["npm", "start"]
