# ok
on: [push]

jobs:
  StartMongoDBAsDocker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ["4.0", "4.2"] 
    name: Start MongoDB ${{ matrix.mongodb-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          name: myDocker/repository
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Start MongoDB As Docker
        uses: ./
        with:
          mongoDBVersion: ${{ matrix.mongodb-version }}
